### ISSUE TITLE
Can't reproduce Turbocharged demo

### ISSUE THREAD

**Issue by hpompom** [ryanmccrickerd/rough_bergomi#2]
I run the code of turbocharged demo, but I find I can not to reproduce the figure, and the mixed estimators  have a very bad performance. Is there something wrong with the part I'm running?
<img width="469" alt="image" src="https://user-images.githubusercontent.com/50010628/163658482-fbc0e2b7-d6e3-418e-8424-24548a1d54a0.png">

**Comment by ryanmccrickerd** [comment]
Hi @hpompom 
The graph you show does not provide statistical evidence for the performance of these estimators - it’s merely a reflection of the numpy seed being used to generate the data behind that particular plot.
The seed used in the demo file is the first one, 0, so is not set to make the mixed estimator look better or worse than others. If you have not changed this seed, then I guess the seed behaviour has changed with numpy version.
In any case, if you would like to provide some statistical evidence of your claim (by e.g. running the type of analysis in our paper), then I will look into it.
Best, Ryan
